# Library Imports

In [ ]:
import pandas as pd
from pycaret.regression import RegressionExperiment
# https://pycaret.gitbook.io/docs/get-started/quickstart#regression

# Read and Preprocess Data

In [26]:
# read data
data = pd.read_csv('Begining_Dataset.csv')

# drop the na rows
data = data.dropna()

# remove columns 10 to 19 except for column 15
# 10 to 19 are the homeless count targets not features
# column 15 is the selected target for this run
drop_idx = list(range(10,15)) + list(range(16,20))
drop_cols = data.columns[drop_idx]
print(drop_cols)
data = data.drop(columns=drop_cols)

# print out some rows
data.head()

Index(['Overall Homeless', 'Overall Homeless Individuals',
       'Overall Homeless People in Families', 'Unsheltered Homeless',
       'Sheltered Total Homeless', 'Overall_Homeless_Individuals_Per_Capita',
       'Overall_Homeless_People_in_Families_Per_Capita',
       'Unsheltered_Homeless_Per_Capita', 'Sheltered_Homeless_Per_Capita'],
      dtype='object')

,Total Population,Median Gross Rent,Median Household Income,Poverty_Rate,Vacancy_Rate,Renter_Household_Rate,Cost_Burdened_Rate,Unemployment_Rate,"Total Year-Round Beds (ES, TH, SH)",Average Temperature,Overall_Homeless_Per_Capita
7,263206,59532,3931531,8.837944,7.921203,39.721806,43.348727,7.143623,988.0,18.4,0.003887
8,294038,69646,4276757,8.086370,7.885972,40.565390,45.259545,6.718333,1019.0,7.1,0.004108
9,289982,72098,4293890,8.044292,8.396699,40.757004,45.706091,6.087872,1007.0,17.2,0.003811
10,289010,73387,4437615,8.016332,8.576839,40.898085,44.809796,5.806139,1023.0,4.5,0.003903
11,287529,75827,4527440,9.103777,8.657760,40.044081,45.932310,5.663429,1028.0,6.7,0.003805

# Run Experiment

In [27]:
s = RegressionExperiment()
s.setup(data,
        target="Overall_Homeless_Per_Capita",
        session_id= 222)
best = s.compare_models()
print(best)

<catboost.core.CatBoostRegressor object at 0x000002C9F0B42090>